//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uerj.br/LDASchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://uerj.br/LDASchema", IsNullable=false)]
public partial class cenarios {
    
    private cenariosCenario[] cenarioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cenario")]
    public cenariosCenario[] cenario {
        get {
            return this.cenarioField;
        }
        set {
            this.cenarioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uerj.br/LDASchema")]
public partial class cenariosCenario {
    
    private string nomeField;
    
    private cenariosCenarioConector[] conectorField;
    
    /// <remarks/>
    public string nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("conector")]
    public cenariosCenarioConector[] conector {
        get {
            return this.conectorField;
        }
        set {
            this.conectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uerj.br/LDASchema")]
public partial class cenariosCenarioConector {
    
    private cenariosCenarioConectorTipo tipoField;
    
    private string cenario_relacionadoField;
    
    /// <remarks/>
    public cenariosCenarioConectorTipo tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <remarks/>
    public string cenario_relacionado {
        get {
            return this.cenario_relacionadoField;
        }
        set {
            this.cenario_relacionadoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uerj.br/LDASchema")]
public enum cenariosCenarioConectorTipo {
    
    /// <remarks/>
    restricao,
    
    /// <remarks/>
    pre_condicao,
    
    /// <remarks/>
    sub_cenario,
}
